rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
notifications:
  email:
    - 4k3nd0@gmail.com
env:
  - PUPPET_VERSION=2.7.21
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.1
  - PUPPET_VERSION=3.3.0